// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f32fa76d-7d4f-42d9-9133-4ede5aef0bd1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_6OtBpo1RW",
    "aws_user_pools_web_client_id": "2ovtjvfe016pork3mru1k172nj",
    "oauth": {}
};


export default awsmobile;
